# -*- coding: utf-8 -*-
"""sanika2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1muhRAZBGoN2RtmCoM6wsoeaEYikin1mg
"""



"""addition of two number

"""

a=10
b=20
c=a+b
print(c)

"""multiplication of two no.s"""

a=2
b=3
c=a*b
print(c)

"""hello world"""

print("hello world")