# -*- coding: utf-8 -*-
"""sanika.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1muhRAZBGoN2RtmCoM6wsoeaEYikin1mg
"""



"""addition of two number

"""

a=10
b=20
c=a+b
print(c)